#!/usr/bin/env python3
# -*- mode: python; indent-tabs-mode: nil -*-

# FlightAware multilateration client

import argparse

import mlat.client.version
from flightaware.client.adeptclient import AdeptConnection, UdpServerConnection
from mlat.client.coordinator import Coordinator
from mlat.client.util import log
from mlat.client import options


def main():
    # piaware will timestamp our log messages itself, suppress the normal logging timestamps
    mlat.client.util.suppress_log_timestamps = True

    parser = argparse.ArgumentParser(description="Client for multilateration.")

    options.make_inputs_group(parser)
    options.make_results_group(parser)

    parser.add_argument('--udp-transport',
                        help="Provide UDP transport information. Expects a host:port:key argument.",
                        required=True)

    args = parser.parse_args()

    log("fa-mlat-client {version} starting up", version=mlat.client.version.CLIENT_VERSION)

    udp_host, udp_port, udp_key = args.udp_transport.split(':')
    udp_port = int(udp_port)
    udp_key = int(udp_key)
    udp_transport = UdpServerConnection(udp_host, udp_port, udp_key)
    log("Using UDP transport to {host}:{port}", host=udp_host, port=udp_port)

    receiver = options.build_receiver_connection(args)
    adept = AdeptConnection(udp_transport)
    outputs = options.build_outputs(args)

    coordinator = Coordinator(receiver=receiver, server=adept, outputs=outputs, freq=options.clock_frequency(args))
    adept.start(coordinator)
    coordinator.run_until(lambda: adept.closed)

if __name__ == '__main__':
    main()
